# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 158f16fa542165370e57ba3287e0d1154a3cd625972df2a914551b3a29004530e944382e336364bd3a3858f46e733f44894f15a880ef3ff442006e082e66d6b6

test:
  secret_key_base: 9020a4aed9ea125f6269683ad1548cde6e534dce044d149d02037178b2861db8d24368651142d5bc5e000f56ad37bf2b568ac158ced17968b3370c717ecb44e4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
